### ISSUE TITLE
Use correct language codes

### ISSUE THREAD

**Issue by strogonoff** [glossarist/glossarist-desktop#49]
Current codes are:

https://github.com/glossarist/glossarist-desktop/blob/master/src/app.ts#L7

```
  'eng': 'English',
  'fra': 'French',
  'ara': 'Arabic',
  'chi': 'Chinese',
  'ces': 'Czech',
  'dan': 'Danish',
  'fin': 'Finnish',
  'ita': 'Italian',
  'ger': 'German',
  'jpn': 'Japanese',
  'kor': 'Korean',
  'msa': 'Malay',
  'nno': 'Norwegian Nynorsk',
  'nob': 'Norwegian Bokmål',
  'pol': 'Polish',
  'por': 'Portuguese',
  'rus': 'Russian',
  'slv': 'Slovenian',
  'spa': 'Spanish',
  'srp': 'Serbian',
  'swe': 'Swedish',
```

**Comment by ronaldtse** [comment]
Reported from TC 211 TMG: App still uses the wrong list of languages:

<img width="213" alt="Screen Shot 2020-07-09 at 11 30 42 AM" src="https://user-images.githubusercontent.com/11865/86993850-a181f700-c1d7-11ea-9974-4067bc0887cd.png">

And this differs from the (correct) list at register.yaml:
https://github.com/geolexica/isotc211-glossary/blob/6ea5e8b0f58c8aaaa9116785152fa267858e3676/register.yaml#L10-L25

```yaml
subregisters:
  eng:
  ara:
  zho:
  dan:
  nld:
  fin:
  fra:
  deu:
  jpn:
  kor:
  msa:
  pol:
  rus:
  spa:
  swe:
```
