### ISSUE TITLE
TC 211 TMG: App still uses the wrong list of languages

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#78]
Reported from TC 211 TMG: App still uses the wrong list of languages:

<img width="213" alt="Screen Shot 2020-07-09 at 11 30 42 AM" src="https://user-images.githubusercontent.com/11865/86993850-a181f700-c1d7-11ea-9974-4067bc0887cd.png">

And this differs from the (correct) list at register.yaml:
https://github.com/geolexica/isotc211-glossary/blob/6ea5e8b0f58c8aaaa9116785152fa267858e3676/register.yaml#L10-L25

```yaml
subregisters:
  eng:
  ara:
  zho:
  dan:
  nld:
  fin:
  fra:
  deu:
  jpn:
  kor:
  msa:
  pol:
  rus:
  spa:
  swe:
```

_Originally posted by @ronaldtse in https://github.com/glossarist/glossarist-desktop/issues/49#issuecomment-655877750_
